version: 2

sources:
  - name: marketing
    database: database
    schema: marketing

    tables:
      - name: channels
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
        columns:
          - name: campaign_id
            tests: [not_null, unique]

      - name: web_orders
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
        columns:
          - name: date
            tests: [not_null]
          - name: country_code
            tests: [not_null]
          - name: campaign_id
            tests: [not_null]

      - name: leads_funnel
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
        columns:
          - name: date
            tests: [not_null]
          - name: country_code
            tests: [not_null]
          - name: campaign_id
            tests: [not_null]
